# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3-node-browsers
    working_directory: ~/deploy


    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: mv .env.ci .env
      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
  deploy:
     docker:
       - image: circleci/php:7.4-node-browsers

     steps:
       - checkout
       - add_ssh_keys:
           fingerprints:
             - "05:92:a6:0c:75:34:a7:29:0b:a7:16:02:7c:a4:4a:df"
       - run:
           name: Ma premiere connexion à ma vm
           command: |
             curl -LO https://deployer.org/deployer.phar
             mv deployer.phar /usr/local/bin/dep
             chmod +x /usr/local/bin/dep
       - run:
           name: Deployer
           command: |
             dep build



workflows:
  version: 2
  notify_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
